config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root to: "pages#home"

  # get 'fishing_spots/index'
  # get 'fishing_spots/show'
  # get 'hints/index'
  resources :fishing_spots, only: [:index, :show] do
    resources :hints, only: [:index]
    resources :discussions, only:[:index, :create] do
    end
  end
  resources :discussions, only:[:show, :destroy, :edit, :update] do
    resources :replies, only:[:create, :edit, :destroy]
  end  
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_discussion.html.erb
<div class="dis-content">
  <div class="column-contain is-8">
    <h3 class="title is-5">Spot Discussion</h3>

    <%= link_to  fishing_spot_path(@fishing_spot) do %>

      <i class="fas fa-arrow-alt-circle-left fa-3x"></i>
    <% end %>
    <div class="discussions">
      <% @discussions.each do |discussion| %>
        <div class="columns-message bb-not-last pv10">
          <div class="column is-8">
            <%= link_to discussion_path(discussion) do %>
              <h3 class="title-dis is-5"><%= discussion.title.capitalize %></h3>
            <% end %>
             <h2 class="con-text"> <%= discussion.content.capitalize %></h2>
              <p class="post"><em><strong class="column-user"><%= discussion.user.name.capitalize %></strong><small>Posted <%= time_ago_in_words(discussion.created_at) %> ago in
                </small>
                </em>
              </p>
              <% if discussion.user == current_user %>
              <%# <%= link_to 'Edit', edit_discussion_path(discussion), class:'button' %>
              <%# <%= link_to fishing_spot_discussions_path,  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "button-disc" do %>
                <%# <i class="fa-solid fa-trash-can"></i> %>
              <%# <% end %> 
          </div>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_discusssions.html.erb
<div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Latest Discussions</h3>
  <div class="discussions">
    <% @discussions.each do |discussion| %>
      <div class="columns bb-not-last pv10">
        <div class="column is-1">
          <%= gravatar_image_tag(discussion.user.email, class:'border-radius-50', size: 48, alt: discussion.user.username) %>
        </div>
        <div class="column is-8">
          <%= link_to discussion do %>
            <h3 class="title is-5"><%= discussion.title %></h3>
          <% end %>
          <div class="content">
            <%= truncate(strip_markdown(discussion.content), length: 140) %>
            <p><em><small>Posted <%= time_ago_in_words(discussion.created_at) %> ago in
              <% if discussion.channel %>
                <%= link_to discussion.channel.channel, discussion.channel %>
              <% end %>
              by <%= discussion.user.username %>
              </small>
              </em>
            </p>
          </div>
        </div>

        <% if discussion_author(discussion) || has_role?(:admin) %>
        <div class="column has-text-right">
          <%= link_to 'Edit', edit_discussion_path(discussion), class:'button' %>
          <%= link_to 'Delete', discussion, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
        </div>
        <% end %>

      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<%# <link rel="manifest" href="/manifest.json"> %>
<%# <meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff"> %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%# <%= image_tag "Fishing onshore 2.png" %> 
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>