config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root to: "pages#home"

  # get 'fishing_spots/index'
  # get 'fishing_spots/show'
  # get 'hints/index'
  resources :fishing_spots, only: [:index, :show] do
    resources :hints, only: [:index]
    resources :discussions, only:[:index, :create] do
    end
  end
  resources :discussions, only:[:show, :destroy, :edit, :update] do
    resources :replies, only:[:create, :edit, :destroy]
  end  
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/fishing_spot.rb
# class GoodnessValidator < ActiveModel::Validator
#   def validate(record)
#     if record.address.nil?
#       validates :latitude, :longitude, presence: true
#       record.errors.add :base, "Both Latitudes and Longitudes must be filled"
#       # record.errors.add :base, "This person is evil"
#     else
#       validates :address, presence: true
#       record.errors.add :base, "Address must be filled"
#     end
#   end
# end

class FishingSpot < ApplicationRecord
  geocoded_by :address
  # Associations
  has_many :prefered_fishing_spots, dependent: :destroy
  has_one_attached :photo

  # Validations
  validates :fishing_activity, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  # validates_with GoodnessValidator
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/fishing_spots_controller.rb
require "json"
require "open-uri"

class FishingSpotsController < ApplicationController
  before_action :set_spot, only: [:show, :photo]

  def index
    # @fishingspots = FishingSpot.order(fishing_activity: :desc)
    if params[:query].present?
      @fishingspots = FishingSpot.where("address ILIKE ?", "%#{params[:query]}%")
    else 
      @fishingspots = FishingSpot.order(fishing_activity: :desc)
    end

    # @fishingspots = FishingSpot.order(fishing_activity: :desc)
  end

  def new
    @fishingspots = FishingSpot.new(fish_params)
    @fishingspot = FishingSpot.save(set_spot)
  end

  def show
    # @fishingspots = FishingSpot.geocoded
    @marker = [{
      lat: @fishingspot.latitude,
      lng: @fishingspot.longitude,
      image_url: helpers.asset_url("logo.png")
    }]

    @fishspot = set_spot
    @location = find_spot
    # Weather Condition
    @condition = @location['current']['condition']['text']
    # Weather Icon
    @icon = @location['current']['condition']['icon']
    # Temperature
    @temperature = @location['current']['temp_c']
    # Wind Speed
    @windspeed = @location['current']['wind_kph']
    # Wind Direction
    winddirection = @location['current']['wind_dir']
    @winddirection = display_direction_fullname(winddirection)
    # Humidity
    @humidity = @location['current']['humidity']
  end

  private

  def set_spot
    @fishingspot = FishingSpot.find(params[:id])
  end

  def fish_params
    params.require(:fishingspots).permit(:address, :fishing_activity, :longitude, :latitude, :photo)
  end

  def find_spot
    url = "https://api.weatherapi.com/v1/current.json?key=7f022012d2f24e53a3f100654221910&q=#{@fishspot.latitude},#{@fishspot.longitude}"
    location_serialized = URI.open(url).read
    location = JSON.parse(location_serialized)
  end

  def display_direction_fullname(direction)
    case direction
    when "N"
      "North"
    when "NNE"
      "North of North-East"
    when "NE"
      "North East"
    when "ENE"
      "East of North-East"
    when "E"
      "East"
    when "ESE"
      "East of South-East"
    when "SE"
      "South East"
    when "SSE"
      "South of South-East"
    when "S"
      "South"
    when "SSW"
      "South of South-West"
    when "SW"
      "South-West"
    when "WSW"
      "West of South-West"
    when "W"
      "West"
    when "WNW"
      "West of North-West"
    when "NW"
      "North-West"
    when "NNW"
      "North of North-West"
    else
      "Cannot Find Wind Direction"
    end
  end
end

app/views/fishing_spots/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/fishing_spots/_info_window.html.erb
<p><%= fishingspot.address %></p>

app/views/fishing_spots/_mapbox.html.erb
<div style="width: 100%; height: 400px;"
    data-controller="map"
    data-map-marker-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  

app/views/fishing_spots/index.html.erb
<div class="container">
  <h1 class="title-fish">Fishing Spots</h1>
  <div class="search">
  <%= form_with url: fishing_spots_path, method: :get, class: "d-flex search-field" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find Your Location"
    %>

    <%= button_tag(type: "submit", class: "btn-fishs btn-default") do %>
        <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>    
  <% end %>
</div>

  <div class="card-container">
    <% @fishingspots.each do |fishing_spot| %>
      <div class="card card-block">
        <div class="card-image">
          <%= cl_image_tag fishing_spot.photo.key, crop: :fill %>
        </div>
        <h3 class="card-address"><%= fishing_spot.address %></h3>
        <div class="card-activity">
          <% for i in 1..fishing_spot.fishing_activity %>
            <i class="fa-solid fa-fish-fins fa-2x"></i>
          <% end %>
        </div>
        <p class="card-text">Fishing Activity is <%= fishing_spot.fishing_activity %></p>
        <%= link_to "Fish Here", fishing_spot_path(fishing_spot), class: "btn-fish"%>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/fishing_spots/show.html.erb
<div class="container-fishingspot">

  <h1 class = "title-fish"><%= @fishspot.address %></h1>

  <%# <div id='map' style='width: 400px; height: 300px;'></div>
  <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoiYW1lZW5haDE0NyIsImEiOiJjbDlmYjM5ZjEwNW0zM29yeG12cWFha2VvIn0.nCfUZJuzLLaP6wPxGuVgFw';
    const map = new mapboxgl.Map({
      container: 'map', // container ID
      style: 'mapbox://styles/mapbox/streets-v11', // style URL
      center: [-74.5, 40], // starting position [lng, lat]
      zoom: 9, // starting zoom
      projection: 'globe' // display the map as a 3D globe
    });
    map.on('style.load', () => {
      map.setFog({}); // Set the default atmosphere style
    });
  </script> %>

  <div class="map"
    data-controller="map"
    data-map-marker-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="button-list">
      <div class="btn-map">
        <%= link_to fishing_spots_path do %>
          <i class="fa-solid fa-rectangle-list"></i>
        <% end %>
      </div>
      <div class="btn-map">
        <%= link_to fishing_spot_hints_path(@fishingspot) do %>
          <i class="fa-solid fa-toolbox"></i>
        <% end %>
      </div>
      <div class="btn-map">
        <button type="button" class="btn-map" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="fa-solid fa-cloud-sun"></i>
        </button>
      </div>
    <div class="btn-map" >
      <%= link_to fishing_spot_discussions_path(@fishingspot) do %>
         <i class="fab fa-rocketchat"></i>
      <% end %>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div style = "background: linear-gradient(60deg, #543ab7 0%, #00acc1 100%);" class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title title-fish-h2" id="exampleModalLabel"><%= @fishspot.address %>'s Fishing Condition</h2>
        </div>
        <div class="modal-body">
          <div class="weather-card">
            <div class="condition">
              <div class="img-icon">
                <img src="<%= @icon %>" alt="Weather Condition" class="icon">
              </div>
              <p class="text-condition-direction"><%= @condition %></p>
            </div>
            <div class="temperature">
              <p class="text-temperature-humidity-speed"><%= @temperature %></p>
              <%= image_tag "celsius.gif", class:"icon-gif" %>
              <%# <img src="../../assets/images/celsius.gif" alt="Temperature" class="icon-gif"> %>
              <%# <i class="fa-solid fa-temperature-half fa-3x"></i> %>
            </div>
            <div class="humidity">
              <p class="text-temperature-humidity-speed"><%= @humidity %> %</p>
              <%= image_tag "water.gif", class:"icon-gif" %>
              <%# <i class="fa-solid fa-droplet fa-3x"></i> %>
              <%# <img src="../../assets/images/drop.gif" alt="Humidity" class="icon-gif"> %>
            </div>
            <div class="speed">
              <p class="text-temperature-humidity-speed"><%= @windspeed %> kph</p>
              <%= image_tag "wind.gif", class:"icon-gif" %>
              <%# <i class="fa-solid fa-wind fa-3x"></i> %>
              <%# <img src="../../assets/images/wind.gif" alt="Wind Speed" class="icon-gif"> %>
            </div>
            <div class="direction">
              <p class="text-condition-direction"><%= @winddirection %></p>
              <%# <i class="fa-regular fa-compass fa-3x"></i> %>
              <%= image_tag "compass.gif", class:"icon-gif" %>
              <%# <img src="../../assets/images/compass.gif" alt="Wind Direction" class="icon-gif"> %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" data-bs-dismiss="modal">
              <i class="fa-solid fa-circle-left"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>